const data = [
  {
    id: 1,
    title: "코딩전문가와 함께하는 코딩여행",
    image: "/images/popBanner.png",
    category: "개발",
    views: 250,
    likes: 40,
    author: "코딩전문가 문팀장님",
    date: "2024-02-20",
  },
  {
    id: 2,
    title: "Python으로 데이터 분석 및 시각화",
    image: "/images/popBanner.png",
    category: "Python",
    views: 180,
    likes: 30,
    author: "박분석",
    date: "2024-02-18",
  },
  {
    id: 3,
    title: "React와 Next.js를 활용한 웹 개발",
    image: "/images/popBanner.png",
    category: "프론트엔드",
    views: 300,
    likes: 50,
    author: "최제작",
    date: "2024-02-15",
  },
  {
    id: 4,
    title: "자동화 스크립트 제작: Python & ChatGPT 활용",
    image: "/images/popBanner.png",
    category: "자동화",
    views: 220,
    likes: 45,
    author: "이지혜",
    date: "2024-02-17",
  },
  {
    id: 5,
    title: "Node.js로 서버 구축하기",
    image: "/images/popBanner.png",
    category: "백엔드",
    views: 190,
    likes: 25,
    author: "홍길동",
    date: "2024-02-14",
  },
  {
    id: 6,
    title: "TypeScript의 기본 개념과 활용",
    image: "/images/popBanner.png",
    category: "프론트엔드",
    views: 160,
    likes: 20,
    author: "고길동",
    date: "2024-02-13",
  },
  {
    id: 7,
    title: "Git과 GitHub를 활용한 협업 전략",
    image: "/images/popBanner.png",
    category: "버전관리",
    views: 170,
    likes: 28,
    author: "둘리",
    date: "2024-02-12",
  },
  {
    id: 8,
    title: "SQL과 NoSQL 비교 및 활용 사례",
    image: "/images/popBanner.png",
    category: "데이터베이스",
    views: 210,
    likes: 35,
    author: "마이콜",
    date: "2024-02-11",
  },
  {
    id: 9,
    title: "React 상태관리: Zustand와 Redux 비교",
    image: "/images/popBanner.png",
    category: "프론트엔드",
    views: 220,
    likes: 37,
    author: "도우너",
    date: "2024-02-10",
  },
  {
    id: 10,
    title: "Docker와 Kubernetes를 활용한 배포 자동화",
    image: "/images/popBanner.png",
    category: "DevOps",
    views: 250,
    likes: 50,
    author: "또치",
    date: "2024-02-09",
  },
  {
    id: 11,
    title: "GraphQL vs REST API 비교",
    image: "/images/popBanner.png",
    category: "백엔드",
    views: 200,
    likes: 30,
    author: "희동이",
    date: "2024-02-08",
  },
  {
    id: 12,
    title: "NestJS로 확장 가능한 서버 개발하기",
    image: "/images/popBanner.png",
    category: "백엔드",
    views: 180,
    likes: 25,
    author: "영희",
    date: "2024-02-07",
  },
  {
    id: 13,
    title: "HTML5와 CSS3를 활용한 반응형 웹 디자인",
    image: "/images/popBanner.png",
    category: "프론트엔드",
    views: 140,
    likes: 18,
    author: "철수",
    date: "2024-02-06",
  },
  {
    id: 14,
    title: "JavaScript 비동기 처리: Async/Await 완벽 이해",
    image: "/images/popBanner.png",
    category: "프론트엔드",
    views: 190,
    likes: 32,
    author: "맹구",
    date: "2024-02-05",
  },
  {
    id: 15,
    title: "Machine Learning 기초 및 Scikit-Learn 활용",
    image: "/images/popBanner.png",
    category: "AI/ML",
    views: 230,
    likes: 45,
    author: "훈이",
    date: "2024-02-04",
  },
  {
    id: 16,
    title: "Go 언어의 특징과 웹 개발 활용법",
    image: "/images/popBanner.png",
    category: "백엔드",
    views: 170,
    likes: 29,
    author: "유리",
    date: "2024-02-03",
  },
  {
    id: 17,
    title: "WebAssembly(WASM)와 성능 최적화",
    image: "/images/popBanner.png",
    category: "프론트엔드",
    views: 200,
    likes: 35,
    author: "짱구",
    date: "2024-02-02",
  },
  {
    id: 18,
    title: "Python FastAPI를 이용한 경량 백엔드 구축",
    image: "/images/popBanner.png",
    category: "백엔드",
    views: 210,
    likes: 40,
    author: "봉미선",
    date: "2024-02-01",
  },
  {
    id: 19,
    title: "TensorFlow와 PyTorch로 딥러닝 시작하기",
    image: "/images/popBanner.png",
    category: "AI/ML",
    views: 3000,
    likes: 55,
    author: "신형만",
    date: "2024-01-31",
  },
  {
    id: 20,
    title: "C++를 활용한 고성능 프로그래밍",
    image: "/images/popBanner.png",
    category: "시스템 프로그래밍",
    views: 280,
    likes: 50,
    author: "흰둥이",
    date: "2024-01-30",
  },
  {
    id: 21,
    title: "ASP를 활용한 비동기 시험 프로그래밍",
    image: "/images/popBanner.png",
    category: "실기 처리",
    views: 282,
    likes: 53,
    author: "친절한 광체씨",
    date: "2025-02-25",
  },
];

export default data;
