const Data = [
  {
    id: 1,
    category: "여행",
    title: "제주도의 숨은 명소 탐방",
    content: "제주도의 숨겨진 아름다운 장소를 찾아 떠나는 여행 이야기입니다.",
    author: "user1",
  },
  {
    id: 2,
    category: "게임",
    title: "메이플스토리 직업 추천",
    content: "초보자를 위한 메이플스토리 직업 추천 가이드.",
    author: "user2",
  },
  {
    id: 3,
    category: "음악",
    title: "K-POP 최신 인기곡 소개",
    content: "요즘 핫한 K-POP 곡과 아티스트에 대한 이야기.",
    author: "user3",
  },
  {
    id: 4,
    category: "여행",
    title: "유럽 배낭여행 준비물",
    content: "유럽 배낭여행을 떠나기 전 챙겨야 할 필수 아이템.",
    author: "user4",
  },
  {
    id: 5,
    category: "게임",
    title: "메이플스토리 보스 공략",
    content: "초보자도 쉽게 따라할 수 있는 보스 공략법.",
    author: "user5",
  },
  {
    id: 6,
    category: "음악",
    title: "클래식 음악 입문 추천",
    content: "처음 클래식 음악을 접하는 분들을 위한 추천 곡.",
    author: "user6",
  },
  {
    id: 7,
    category: "여행",
    title: "국내 숨은 해변 추천",
    content: "여름 휴가철에 가기 좋은 국내 해변 리스트.",
    author: "user7",
  },
  {
    id: 8,
    category: "게임",
    title: "메이플스토리 장비 강화 비법",
    content: "장비 강화 확률을 높이는 꿀팁 공개.",
    author: "user8",
  },
  {
    id: 9,
    category: "음악",
    title: "인디 음악 추천",
    content: "인디씬에서 떠오르는 아티스트와 곡 소개.",
    author: "user9",
  },
  {
    id: 10,
    category: "여행",
    title: "서울 근교 당일치기 여행지",
    content: "주말에 가기 좋은 서울 근교 여행지 추천.",
    author: "user10",
  },
  {
    id: 11,
    category: "게임",
    title: "메이플스토리 이벤트 참여 방법",
    content: "효율적으로 이벤트에 참여하고 보상을 받는 방법.",
    author: "user11",
  },
  {
    id: 12,
    category: "음악",
    title: "록 음악의 전설",
    content: "록 음악의 황금기를 이끈 전설적인 밴드와 곡.",
    author: "user12",
  },
  {
    id: 13,
    category: "여행",
    title: "일본 온천 여행 가이드",
    content: "일본 온천을 제대로 즐길 수 있는 팁과 추천 장소.",
    author: "user13",
  },
  {
    id: 14,
    category: "게임",
    title: "메이플스토리 퀘스트 효율적으로 완료하기",
    content: "퀘스트를 빠르고 쉽게 완료하는 노하우.",
    author: "user14",
  },
  {
    id: 15,
    category: "음악",
    title: "힙합 음악 추천",
    content: "요즘 인기 있는 힙합 곡과 아티스트 소개.",
    author: "user15",
  },
  {
    id: 16,
    category: "여행",
    title: "동남아 여행 추천 도시",
    content: "동남아에서 꼭 가봐야 할 인기 여행지.",
    author: "user16",
  },
  {
    id: 17,
    category: "게임",
    title: "메이플스토리 캐릭터 육성법",
    content: "효율적으로 캐릭터를 성장시키는 방법.",
    author: "user17",
  },
  {
    id: 18,
    category: "음악",
    title: "재즈 명곡 추천",
    content: "편안한 분위기를 만들어 주는 재즈 명곡.",
    author: "user18",
  },
  {
    id: 19,
    category: "여행",
    title: "겨울철 국내 여행지",
    content: "추운 겨울에 가기 좋은 여행지와 활동 추천.",
    author: "user19",
  },
  {
    id: 20,
    category: "게임",
    title: "메이플스토리 코디 아이디어",
    content: "개성 있는 캐릭터 코디를 위한 아이디어.",
    author: "user20",
  },
  {
    id: 21,
    category: "음악",
    title: "전자 음악 추천",
    content: "파티 분위기를 살려주는 인기 전자 음악.",
    author: "user21",
  },
  {
    id: 22,
    category: "여행",
    title: "북유럽 자연 여행기",
    content: "북유럽의 대자연을 즐길 수 있는 여행 코스.",
    author: "user22",
  },
  {
    id: 23,
    category: "게임",
    title: "메이플스토리 경제 시스템 이해하기",
    content: "게임 내에서 돈을 효율적으로 관리하는 법.",
    author: "user23",
  },
  {
    id: 24,
    category: "음악",
    title: "팝 음악 히트곡",
    content: "대중적으로 사랑받는 팝 음악 히트곡들.",
    author: "user24",
  },
  {
    id: 25,
    category: "여행",
    title: "남미의 숨겨진 보물",
    content: "남미에서 꼭 가봐야 할 숨겨진 명소.",
    author: "user25",
  },
  {
    id: 26,
    category: "게임",
    title: "메이플스토리 파티 플레이 전략",
    content: "친구들과 파티를 구성해 플레이하는 전략.",
    author: "user26",
  },
  {
    id: 27,
    category: "음악",
    title: "발라드 명곡 추천",
    content: "감성을 자극하는 발라드 명곡.",
    author: "user27",
  },
  {
    id: 28,
    category: "여행",
    title: "오세아니아의 자연 탐험",
    content: "호주와 뉴질랜드의 자연 명소를 탐험하는 여정.",
    author: "user28",
  },
  {
    id: 29,
    category: "게임",
    title: "메이플스토리 초보자 가이드",
    content: "처음 시작하는 분들을 위한 게임 가이드.",
    author: "user29",
  },
  {
    id: 30,
    category: "음악",
    title: "한국 전통 음악 소개",
    content: "한국의 아름다운 전통 음악과 악기 소개.",
    author: "user30",
  },
];

export default Data;
